package com.jiewen.modules.upload.entity;

import java.sql.Timestamp;

import com.jiewen.jwp.base.entity.DataEntity;

public class SysFile extends DataEntity {

    public SysFile() {
        super();
    }

    public SysFile(String id) {
        super(id);
    }

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_file.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_file.saved_name
     *
     * @mbg.generated
     */
    private String savedName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_file.file_size
     *
     * @mbg.generated
     */
    private long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * sys_file.flie_path
     *
     * @mbg.generated
     */
    private String filePath;

    private String fileMd5;

    private String fileProgress;

    private Timestamp uploadTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * sys_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_file.file_name
     *
     * @return the value of sys_file.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_file.file_name
     *
     * @param fileName
     *            the value for sys_file.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_file.saved_name
     *
     * @return the value of sys_file.saved_name
     *
     * @mbg.generated
     */
    public String getSavedName() {
        return savedName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_file.saved_name
     *
     * @param savedName
     *            the value for sys_file.saved_name
     *
     * @mbg.generated
     */
    public void setSavedName(String savedName) {
        this.savedName = savedName == null ? null : savedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_file.file_size
     *
     * @return the value of sys_file.file_size
     *
     * @mbg.generated
     */
    public long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_file.file_size
     *
     * @param fileSize
     *            the value for sys_file.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column sys_file.flie_path
     *
     * @return the value of sys_file.flie_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column sys_file.flie_path
     *
     * @param fliePath
     *            the value for sys_file.flie_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    public String getFileMd5() {
        return fileMd5;
    }

    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    public String getFileProgress() {
        return fileProgress;
    }

    public void setFileProgress(String fileProgress) {
        this.fileProgress = fileProgress;
    }

    public Timestamp getUploadTime() {
        return uploadTime;
    }

    public void setUploadTime(Timestamp uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * sys_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fileName=").append(fileName);
        sb.append(", savedName=").append(savedName);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", filePath=").append(filePath);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}
